### PR TITLE
UI: Fixed broken link in modal header

### LINKED ISSUE #9856: Non-functional link in guiconfig.inc modal header (system_advanced_admin.php)
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

When saving "System - Settings - Administration" settings, there is a modal with information about updating the backup Server in a HA setup.

The link reference seems to be broken in the header of this modal:

Image

https://github.com/opnsense/core/blob/1156faee1df99f4d010520ac0f074cb6266864a6/src/www/guiconfig.inc#L298-L316

**To Reproduce**

- Have a HA enabled OPNsense setup (I suppose?)
- Go to "System Settings Administration"
- Change Deployment type from "Production" to "Development"
- Press Save
- See Modal header

**Expected behavior**

Either no link or a working link in the modal header.

**Software version used and hardware type if relevant, e.g.:**

OPNsense 26.1.2 (master though)

### PR DESCRIPTION
**Pull request by TomWalraven**
Fixed a broken link that appears in a modal header when you enable high availability and change deployment type in System: Settings: Administration. The issue was caused by html_safe() not being able to parse the link correctly. This is resolved by using json_encode() instead.

Fixes: #9856

### CODE REVIEW

File: src/www/system_advanced_admin.php [hunk 1]
```diff
@@ -481,7 +481,7 @@
     if (isset($restart_webgui) && $restart_webgui): ?>
         BootstrapDialog.show({
             type:BootstrapDialog.TYPE_INFO,
-            title: '<?= html_safe($savemsg) ?>',
+            title: <?= json_encode($savemsg) ?>,
```
Comment (fichtner) [inline src/www/system_advanced_admin.php]: This is fair although a bit weird from a historical perspective injecting a link into the header (the savemsg is supposed to be a message for an alert box). To avoid future potential for XSS I'd prefer a direct call and...

```suggestion
            title: <?= json_encode(get_std_save_message()) ?>,
```

Comment (fichtner) [reply src/www/system_advanced_admin.php]: ... ok that's it. Some pages used $savemsg as a GET variable:

```
# git grep savemsg src/www | grep GET
src/www/firewall_scrub.php:    if (!empty($_GET['savemsg'])) {
src/www/system_general.php:    if (isset($_GET['savemsg'])) {
src/www/system_general.php:        $savemsg = htmlspecialchars(gettext($_GET['savemsg']));
src/www/system_usermanager_passwordmg.php:    if (isset($_GET['savemsg'])) {
src/www/system_usermanager_passwordmg.php:        $savemsg = htmlspecialchars(sprintf(gettext($_GET['savemsg']), $username));
```

but not this one :)

**Review by fichtner — APPROVED** [review]
thanks!

File: src/www/system_advanced_admin.php (hunk 1 above)
Comment (TomWalraven) [reply src/www/system_advanced_admin.php]: Thank you for reviewing, I've committed your suggestion so I hope it's fine like this.
